---

- name: Clean Up
  hosts: all

  pre_tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:

  tasks:
    - name: Parse role metadata
      ansible.builtin.set_fact:
        role_meta: "{{ lookup('file', '../../meta/main.yml') | from_yaml }}"
      delegate_to: localhost

    - name: Include role
      ansible.builtin.include_role:
        name: "ansible-{{ role_meta.galaxy_info.role_name | replace('_', '-') }}"
      vars:
        state: absent

- name: Cleanup
  hosts: localhost

  tasks:
    - name: Remove boot_analysis
      ansible.builtin.file:
        path: boot_analysis
        state: absent

...
