---

- name: Prepare
  hosts: all
  gather_facts: false
  vars:
    ansible_ssh_user: root
  tasks:
    - name: Gather system info
      ansible.builtin.raw: uname
      register: raw_uname
      changed_when: false
      failed_when: false

    # TODO use preconfigured images instead
    - name: Bootstrap python for Ansible
      ansible.builtin.raw: |
        /bin/bash -c "command -v python3 python || (
        command -v apk >/dev/null && apk add --no-progress --update python3 ||
        (test -e /usr/bin/dnf && dnf install -y python3) ||
        (test -e /usr/bin/apt && (apt -y update && apt install -y python3-minimal)) ||
        (test -e /usr/bin/yum && yum -y -qq install python3) ||
        (test -e /usr/sbin/pkg && env ASSUME_ALWAYS_YES=yes pkg update && env ASSUME_ALWAYS_YES=yes pkg install python3) ||
        (test -e /usr/sbin/pkg_add && /usr/sbin/pkg_add -U -I -x python%3.9) ||
        (test -e /usr/bin/pacman && /usr/bin/pacman -Sy python3 --noconfirm --quiet) ||
        echo 'Warning: Python not bootstrapped due to unknown platform.'
        )"
      changed_when: false
      when: raw_uname.rc == 0 and raw_uname.stdout | trim == "Linux"

    # INFO https://github.com/rocky-linux/sig-cloud-instance-images/issues/56
    - name: "Get file stats for /etc/shadow"
      ansible.builtin.stat:
        path: "/etc/shadow"
      register: "shadow"

    - name: "Fix permissions for /etc/shadow"
      ansible.builtin.file:
        path: "/etc/shadow"
        owner: "root"
        group: "{{ shadow.stat.gr_name }}"
        mode: "0640"
      when: "not shadow.stat.rusr"

    - name: Ensure sudo is installed
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Gather facts
      ansible.builtin.setup:

    - name: Create ansible user
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        state: present
        create_home: true

    - name: Add ansible user to the correct sudoers group based on OS family
      ansible.builtin.user:
        name: ansible
        groups: "{{ 'wheel' if ansible_facts['os_family'] == 'RedHat' else 'sudo' }}"
        append: true

    - name: Set passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible
        line: "ansible ALL=(ALL) NOPASSWD: ALL"
        validate: '/usr/sbin/visudo -cf %s'
        state: present
        create: true
        owner: root
        group: root
        mode: "0644"

...
