---
- name: Prepare
  hosts: all
  gather_facts: false
  vars:
    remote_user: root
  tasks:
    - name: Gather system info
      ansible.builtin.raw: uname
      register: raw_uname
      changed_when: false
      failed_when: false

    - name: Bootstrap python for Ansible
      ansible.builtin.raw: |
        /bin/bash -c "command -v python3 python || (
        command -v apk >/dev/null && apk add --no-progress --update python3 ||
        (test -e /usr/bin/dnf && dnf install -y python3) ||
        (test -e /usr/bin/apt && (apt -y update && apt install -y python3-minimal)) ||
        (test -e /usr/bin/yum && yum -y -qq install python3) ||
        (test -e /usr/sbin/pkg && env ASSUME_ALWAYS_YES=yes pkg update && env ASSUME_ALWAYS_YES=yes pkg install python3) ||
        (test -e /usr/sbin/pkg_add && /usr/sbin/pkg_add -U -I -x python%3.9) ||
        (test -e /usr/bin/pacman && /usr/bin/pacman -Sy python3 --noconfirm --quiet) ||
        echo 'Warning: Python not bootstrapped due to unknown platform.'
        )"
      changed_when: false
      when: raw_uname.rc == 0 and raw_uname.stdout | trim == "Linux"

    - name: Ensure sudo is installed
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Gather facts
      ansible.builtin.setup:

    - name: Create ansible user
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        state: present
        create_home: true

    - name: Add ansible user to the correct sudoers group based on OS family
      ansible.builtin.user:
        name: ansible
        groups: "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"
        append: true

    - name: Ensure ansible users .ssh dir exists
      ansible.builtin.file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: "0644"

    - name: Set authorized_keys for ansible user
      ansible.builtin.copy:
        dest: "/home/ansible/.ssh/authorized_keys"
        content: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        owner: ansible
        group: ansible
        mode: '0600'

...
