---

- name: Prepare
  hosts: all
  gather_facts: false
  vars:
    ansible_ssh_user: root
    locale_lang: en_US.UTF-8
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Remove fqdn from localhost entry
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1\s+{{ inventory_hostname | regex_escape }}(?:\s|$)'
        state: absent
        unsafe_writes: true

    # ipa-config role seems to require it
    - name: Add container fqdn to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: >-
          {{ ansible_facts.default_ipv4.address }}
          {{ inventory_hostname }}
          {{ inventory_hostname_short }}
        insertbefore: BOF
        state: present
        unsafe_writes: true

    - name: Create ansible user
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        state: present
        create_home: true

    - name: Add ansible user to the correct sudoers group based on os family
      ansible.builtin.user:
        name: ansible
        groups: "{{ 'wheel' if ansible_facts.os_family | lower == 'redhat' else 'sudo' }}"
        append: true

    - name: Set passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible
        line: "ansible ALL=(ALL) NOPASSWD: ALL"
        validate: '/usr/sbin/visudo -cf %s'
        state: present
        create: true
        owner: root
        group: root
        mode: "0644"


    - name: Configure locals on debian based systems
      when: ansible_facts.os_family | lower == "debian"
      block:
        - name: Install locales package on debian family
          ansible.builtin.apt:
            name: locales
            state: present
            update_cache: true

        - name: Generate locales
          community.general.locale_gen:
            name: "{{ locale_lang }}"
            state: present
          register: local_gen_result

        - name: Set system locale
          when: local_gen_result.changed  # noqa: no-handler
          ansible.builtin.command:
            cmd: update-locale LANG={{ locale_lang }}
          register: locals_result
          changed_when: locals_result.rc == 0

...
