---

- name: Prepare
  hosts: all
  gather_facts: false
  vars:
    ansible_ssh_user: root
  tasks:
    # TODO use preconfigured images instead
    # INFO https://github.com/rocky-linux/sig-cloud-instance-images/issues/56
    - name: "Get file stats for /etc/shadow"
      ansible.builtin.stat:
        path: "/etc/shadow"
      register: "shadow"

    - name: "Fix permissions for /etc/shadow"
      ansible.builtin.file:
        path: "/etc/shadow"
        owner: "root"
        group: "{{ shadow.stat.gr_name }}"
        mode: "0640"
      when: "not shadow.stat.rusr"

    - name: Gather facts
      ansible.builtin.setup:

    - name: Create ansible user
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        state: present
        create_home: true

    - name: Add ansible user to the correct sudoers group based on OS family
      ansible.builtin.user:
        name: ansible
        groups: "{{ 'wheel' if ansible_facts.os_family == 'RedHat' else 'sudo' }}"
        append: true

    - name: Set passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible
        line: "ansible ALL=(ALL) NOPASSWD: ALL"
        validate: '/usr/sbin/visudo -cf %s'
        state: present
        create: true
        owner: root
        group: root
        mode: "0644"

    - name: Ensure curl-minimal is absent
      when: ansible_facts.distribution | lower != "fedora"
      ansible.builtin.package:
        name: curl-minimal
        state: absent

    - name: Install gnupg and dbus
      become: true
      ansible.builtin.package:
        name:
          - gnupg
          - gnupg2
          - dbus
        state: present
        update_cache: true

    - name: Ensure system-wide GnuPG config directory exists
      become: true
      ansible.builtin.file:
        path: /etc/gnupg
        state: directory
        mode: '0755'

    - name: Disable keyboxd system-wide (CI / R&D containers)
      become: true
      ansible.builtin.copy:
        dest: /etc/gnupg/gpg.conf
        content: |
          no-use-keyboxd
        owner: root
        group: root
        mode: '0644'

...
