---

- name: Verify
  hosts: all

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Parse role metadata
      ansible.builtin.set_fact:
        role_meta: "{{ lookup('file', '../../meta/main.yml') | from_yaml }}"
      delegate_to: localhost

    - name: Include role
      ansible.builtin.include_role:
        name: "ansible-{{ role_meta.galaxy_info.role_name | replace('_', '-') }}"
        tasks_from: tests

...
